server:
   port = 9999

eureka:
   server:
      host: 172.16.16.68
   client:
      register-with-eureka: false
      fetch-registry: false
      serviceUrl:
         defaultZone: http://${eureka.server.host}:${server.port}/eureka/